export const initialRecipes = {
  meals: [
    {
      idMeal: "52893",
      strMeal: "Apple & Blackberry Crumble",
      strDrinkAlternate: null,
      strCategory: "Dessert",
      strArea: "British",
      strInstructions:
        "Heat oven to 190C/170C fan/gas 5. Tip the flour and sugar into a large bowl. Add the butter, then rub into the flour using your fingertips to make a light breadcrumb texture. Do not overwork it or the crumble will become heavy. Sprinkle the mixture evenly over a baking sheet and bake for 15 mins or until lightly coloured.\r\nMeanwhile, for the compote, peel, core and cut the apples into 2cm dice. Put the butter and sugar in a medium saucepan and melt together over a medium heat. Cook for 3 mins until the mixture turns to a light caramel. Stir in the apples and cook for 3 mins. Add the blackberries and cinnamon, and cook for 3 mins more. Cover, remove from the heat, then leave for 2-3 mins to continue cooking in the warmth of the pan.\r\nTo serve, spoon the warm fruit into an ovenproof gratin dish, top with the crumble mix, then reheat in the oven for 5-10 mins. Serve with vanilla ice cream.",
      strMealThumb:
        "https://www.themealdb.com/images/media/meals/xvsurr1511719182.jpg",
      strTags: "Pudding",
      strYoutube: "https://www.youtube.com/watch?v=4vhcOwVBDO4",
      strIngredient1: "Plain Flour",
      strIngredient2: "Caster Sugar",
      strIngredient3: "Butter",
      strIngredient4: "Braeburn Apples",
      strIngredient5: "Butter",
      strIngredient6: "Demerara Sugar",
      strIngredient7: "Blackberrys",
      strIngredient8: "Cinnamon",
      strIngredient9: "Ice Cream",
      strIngredient10: "",
      strIngredient11: "",
      strIngredient12: "",
      strIngredient13: "",
      strIngredient14: "",
      strIngredient15: "",
      strIngredient16: "",
      strIngredient17: "",
      strIngredient18: "",
      strIngredient19: "",
      strIngredient20: "",
      strMeasure1: "120g",
      strMeasure2: "60g",
      strMeasure3: "60g",
      strMeasure4: "300g",
      strMeasure5: "30g",
      strMeasure6: "30g",
      strMeasure7: "120g",
      strMeasure8: "¼ teaspoon",
      strMeasure9: "to serve",
      strMeasure10: "",
      strMeasure11: "",
      strMeasure12: "",
      strMeasure13: "",
      strMeasure14: "",
      strMeasure15: "",
      strMeasure16: "",
      strMeasure17: "",
      strMeasure18: "",
      strMeasure19: "",
      strMeasure20: "",
      strSource:
        "https://www.bbcgoodfood.com/recipes/778642/apple-and-blackberry-crumble",
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: "52794",
      strMeal: "Vegan Chocolate Cake",
      strDrinkAlternate: null,
      strCategory: "Vegan",
      strArea: "American",
      strInstructions:
        "Simply mix all dry ingredients with wet ingredients and blend altogether. Bake for 45 min on 180 degrees. Decorate with some melted vegan chocolate ",
      strMealThumb:
        "https://www.themealdb.com/images/media/meals/qxutws1486978099.jpg",
      strTags: "Vegan,Chocolate,Cake",
      strYoutube: "https://www.youtube.com/watch?v=C3pAgB7pync",
      strIngredient1: "self raising flour",
      strIngredient2: "coco sugar",
      strIngredient3: "cacao",
      strIngredient4: "baking powder",
      strIngredient5: "flax eggs",
      strIngredient6: "almond milk",
      strIngredient7: "vanilla",
      strIngredient8: "water",
      strIngredient9: "",
      strIngredient10: "",
      strIngredient11: "",
      strIngredient12: "",
      strIngredient13: "",
      strIngredient14: "",
      strIngredient15: "",
      strIngredient16: "",
      strIngredient17: "",
      strIngredient18: "",
      strIngredient19: "",
      strIngredient20: "",
      strMeasure1: "1 1/4 cup",
      strMeasure2: "1/2 cup",
      strMeasure3: "1/3 cup raw",
      strMeasure4: "1 tsp",
      strMeasure5: "2",
      strMeasure6: "1/2 cup",
      strMeasure7: "1 tsp",
      strMeasure8: "1/2 cup boiling",
      strMeasure9: "",
      strMeasure10: "",
      strMeasure11: "",
      strMeasure12: "",
      strMeasure13: "",
      strMeasure14: "",
      strMeasure15: "",
      strMeasure16: "",
      strMeasure17: "",
      strMeasure18: "",
      strMeasure19: "",
      strMeasure20: "",
      strSource: "",
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: "52780",
      strMeal: "Potato Gratin with Chicken",
      strDrinkAlternate: null,
      strCategory: "Chicken",
      strArea: "Unknown",
      strInstructions:
        "15 minute potato gratin with chicken and bacon greens: a gratin always seems more effort and more indulgent than ordinary boiled or roasts, but it doesn't have to take 45mins, it's nice for a change and you can control the calorie content by going with full fat to low fat creme fraiche. (It's always tastes better full fat though obviously!) to serve 4: use 800g of potatoes, finely slice and boil in a pan for about 5-8 mins till firmish, not soft. Finely slice 3 onions and place in an oven dish with 2 tblsp of olive oil and 100ml of chicken stock. Cook till the onions are soft then drain the potatoes and pour onto the onions. Season and spoon over cream or creme fraiche till all is covered but not swimming. Grate Parmesan over the top then finish under the grill till nicely golden. serve with chicken and bacon, peas and spinach.",
      strMealThumb:
        "https://www.themealdb.com/images/media/meals/qwrtut1468418027.jpg",
      strTags: null,
      strYoutube: "https://www.youtube.com/watch?v=p3u8eiy3yHI",
      strIngredient1: "Potatoes",
      strIngredient2: "Onions",
      strIngredient3: "Olive Oil",
      strIngredient4: "Chicken Stock",
      strIngredient5: "Creme Fraiche",
      strIngredient6: "Parmesan",
      strIngredient7: "Chicken Breasts",
      strIngredient8: "Bacon",
      strIngredient9: "Spinach",
      strIngredient10: "Peas",
      strIngredient11: "",
      strIngredient12: "",
      strIngredient13: "",
      strIngredient14: "",
      strIngredient15: "",
      strIngredient16: null,
      strIngredient17: null,
      strIngredient18: null,
      strIngredient19: null,
      strIngredient20: null,
      strMeasure1: "800g",
      strMeasure2: "3",
      strMeasure3: "2 tblsp",
      strMeasure4: "100ml",
      strMeasure5: "1 pot",
      strMeasure6: "Topping",
      strMeasure7: "4",
      strMeasure8: "4",
      strMeasure9: "Topping",
      strMeasure10: "Topping",
      strMeasure11: "",
      strMeasure12: "",
      strMeasure13: "",
      strMeasure14: "",
      strMeasure15: "",
      strMeasure16: null,
      strMeasure17: null,
      strMeasure18: null,
      strMeasure19: null,
      strMeasure20: null,
      strSource: "https://www.instagram.com/p/BHxR7hYBJ6P",
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: "52969",
      strMeal: "Chakchouka ",
      strDrinkAlternate: null,
      strCategory: "Miscellaneous",
      strArea: "Tunisian",
      strInstructions:
        "In a large cast iron skillet or sauté pan with a lid, heat oil over medium high heat. Add the onion and sauté for 2-3 minutes, until softened. Add the peppers and garlic, and sauté for an additional 3-5 minutes. Add the tomatoes, cumin, paprika, salt, and chili powder. Mix well and bring the mixture to a simmer. Reduce the heat to medium low and continue to simmer, uncovered, 10-15 minutes until the mixture has thickened to your desired consistency. (Taste the sauce at this point and adjust for salt and spice, as desired.) Using the back of a spoon, make four craters in the mixture, large enough to hold an egg. Crack one egg into each of the craters. Cover the skillet and simmer for 5-7 minutes, until the eggs have set. Serve immediately with crusty bread or pita.",
      strMealThumb:
        "https://www.themealdb.com/images/media/meals/gpz67p1560458984.jpg",
      strTags: null,
      strYoutube: "https://www.youtube.com/watch?v=EHKNu93MSx4",
      strIngredient1: "Tomatoes",
      strIngredient2: "Olive Oil",
      strIngredient3: "Onion",
      strIngredient4: "Red Pepper",
      strIngredient5: "Green Pepper",
      strIngredient6: "Garlic",
      strIngredient7: "Cumin",
      strIngredient8: "Paprika",
      strIngredient9: "Salt",
      strIngredient10: "Chili Powder",
      strIngredient11: "Eggs",
      strIngredient12: "",
      strIngredient13: "",
      strIngredient14: "",
      strIngredient15: "",
      strIngredient16: "",
      strIngredient17: "",
      strIngredient18: "",
      strIngredient19: "",
      strIngredient20: "",
      strMeasure1: "4",
      strMeasure2: "2 tbs",
      strMeasure3: "1 Diced",
      strMeasure4: "1 sliced",
      strMeasure5: "1 sliced",
      strMeasure6: "3 Cloves Crushed",
      strMeasure7: "1 tsp ",
      strMeasure8: "1 tsp ",
      strMeasure9: "3/4 teaspoon",
      strMeasure10: "1/2 teaspoon",
      strMeasure11: "4",
      strMeasure12: " ",
      strMeasure13: " ",
      strMeasure14: " ",
      strMeasure15: " ",
      strMeasure16: " ",
      strMeasure17: " ",
      strMeasure18: " ",
      strMeasure19: " ",
      strMeasure20: " ",
      strSource: "https://www.curiouscuisiniere.com/chakchouka/",
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: "52821",
      strMeal: "Laksa King Prawn Noodles",
      strDrinkAlternate: null,
      strCategory: "Seafood",
      strArea: "Malaysian",
      strInstructions:
        "Heat the oil in a medium saucepan and add the chilli. Cook for 1 min, then add the curry paste, stir and cook for 1 min more. Dissolve the stock cube in a large jug in 700ml boiling water, then pour into the pan and stir to combine. Tip in the coconut milk and bring to the boil.\r\nAdd the fish sauce and a little seasoning. Toss in the noodles and cook for a further 3-4 mins until softening. Squeeze in the lime juice, add the prawns and cook through until warm, about 2-3 mins. Scatter over some of the coriander.\r\nServe in bowls with the remaining coriander and lime wedges on top for squeezing over.",
      strMealThumb:
        "https://www.themealdb.com/images/media/meals/rvypwy1503069308.jpg",
      strTags: "Shellfish,Seafood",
      strYoutube: "https://www.youtube.com/watch?v=OcarztU8cYo",
      strIngredient1: "Olive Oil",
      strIngredient2: "red chili",
      strIngredient3: "Thai red curry paste",
      strIngredient4: "vegetable stock cube",
      strIngredient5: "coconut milk",
      strIngredient6: "fish sauce",
      strIngredient7: "rice noodles",
      strIngredient8: "lime",
      strIngredient9: "king prawns",
      strIngredient10: "coriander",
      strIngredient11: "",
      strIngredient12: "",
      strIngredient13: "",
      strIngredient14: "",
      strIngredient15: "",
      strIngredient16: "",
      strIngredient17: "",
      strIngredient18: "",
      strIngredient19: "",
      strIngredient20: "",
      strMeasure1: "1 tbsp",
      strMeasure2: "1 finely sliced",
      strMeasure3: "2 ½ tbsp",
      strMeasure4: "1",
      strMeasure5: "400ml can",
      strMeasure6: "2 tsp",
      strMeasure7: "100g",
      strMeasure8: "2 juice of 1, the other halved",
      strMeasure9: "150g",
      strMeasure10: "½ small pack",
      strMeasure11: "",
      strMeasure12: "",
      strMeasure13: "",
      strMeasure14: "",
      strMeasure15: "",
      strMeasure16: "",
      strMeasure17: "",
      strMeasure18: "",
      strMeasure19: "",
      strMeasure20: "",
      strSource: "https://www.bbcgoodfood.com/recipes/prawn-laksa-curry-bowl",
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: "52870",
      strMeal: "Chickpea Fajitas",
      strDrinkAlternate: null,
      strCategory: "Vegetarian",
      strArea: "Mexican",
      strInstructions:
        "Heat oven to 200C/180C fan/gas 6 and line a baking tray with foil. Drain the chickpeas, pat dry and tip onto the prepared baking tray. Add the oil and paprika, toss to coat, then roast for 20-25 mins until browned and crisp, shaking halfway through cooking.\r\n\r\nMeanwhile, put the tomatoes and onion in a small bowl with the vinegar and set aside to pickle. Put the avocado in another bowl and mash with a fork, leaving some larger chunks. Stir in the lime juice and season well. Mix the soured cream with the harissa and set aside until ready to serve.\r\n\r\nHeat a griddle pan until nearly smoking. Add the tortillas , one at a time, charring each side until hot with griddle lines. \r\n\r\nPut everything on the table and build the fajitas : spread a little of the harissa cream over the tortilla, top with roasted chickpeas, guacamole, pickled salsa and coriander, if you like. Serve with the lime wedges for squeezing over.",
      strMealThumb:
        "https://www.themealdb.com/images/media/meals/tvtxpq1511464705.jpg",
      strTags: "Vegetarian",
      strYoutube: "https://www.youtube.com/watch?v=LGY3V7EGpT0",
      strIngredient1: "Chickpeas",
      strIngredient2: "Olive Oil",
      strIngredient3: "Paprika",
      strIngredient4: "Tomatoes",
      strIngredient5: "Red Onions",
      strIngredient6: "Red Wine Vinegar",
      strIngredient7: "Avocado",
      strIngredient8: "Lime",
      strIngredient9: "Lime",
      strIngredient10: "Sour Cream",
      strIngredient11: "Harissa Spice",
      strIngredient12: "Corn Tortillas",
      strIngredient13: "Coriander",
      strIngredient14: "",
      strIngredient15: "",
      strIngredient16: "",
      strIngredient17: "",
      strIngredient18: "",
      strIngredient19: "",
      strIngredient20: "",
      strMeasure1: "400g",
      strMeasure2: "1 tblsp ",
      strMeasure3: "pinch",
      strMeasure4: "2 small cut chunks",
      strMeasure5: "1 finely sliced",
      strMeasure6: "2 tsp",
      strMeasure7: "1",
      strMeasure8: "Juice of 1",
      strMeasure9: "Chopped",
      strMeasure10: "100g ",
      strMeasure11: "2 tsp",
      strMeasure12: "4",
      strMeasure13: "to serve",
      strMeasure14: "",
      strMeasure15: "",
      strMeasure16: "",
      strMeasure17: "",
      strMeasure18: "",
      strMeasure19: "",
      strMeasure20: "",
      strSource: "https://www.bbcgoodfood.com/recipes/chickpea-fajitas",
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: "52891",
      strMeal: "Blackberry Fool",
      strDrinkAlternate: null,
      strCategory: "Dessert",
      strArea: "British",
      strInstructions:
        "For the biscuits, preheat the oven to 200C/180C (fan)/Gas 6 and line two large baking trays with baking parchment. Scatter the nuts over a baking tray and roast in the oven for 6-8 minutes, or until golden-brown. Watch them carefully so that they don’t have a chance to burn. Remove from the oven, tip onto a board and leave to cool.\r\nPut the butter and sugar in a large bowl and beat with a wooden spoon until light and creamy. Roughly chop the cooled nuts and add to the creamed butter and sugar, along with the lemon zest, flour and baking powder. Stir well until the mixture comes together and forms a ball – you may need to use your hands.\r\nDivide the biscuit dough into 24 even pieces and roll into small balls. Place the balls the prepared baking trays, spaced well apart to allow for spreading.\r\nPress the biscuits to flatten to around 1cm/½in thick. Bake the biscuits, one tray at a time, for 12 minutes or until very pale golden-brown. Leave to cool on the trays. They will be very soft when you take them out of the oven, but will crisp as they cool.\r\nStore in an airtight tin and eat within five days.\r\nFor the fool, rinse the blackberries in a colander to wash away any dust or dirt. Put the blackberries in a non-stick saucepan and sprinkle over the caster sugar.\r\nStir in the lemon juice and heat gently for two minutes, or until the blackberries begin to soften and release their juices. Remove and reserve 12 blackberries for decoration and continue cooking the rest.\r\nSimmer the blackberries very gently for 15 minutes, stirring regularly until very soft and squidgy. Remove from the heat and press the berries and juice through a sieve over a bowl, using the bottom of a ladle to help you extract as much of the purée as possible. Leave the purée to cool and discard the seeds. You should end up with around 325ml/11fl oz of purée.\r\nPut the cream and yoghurt in a large bowl and whip with an electric whisk until soft peaks form when the whisk is removed from the bowl – the acidity of the fruit will thicken the cream further, so don’t take it too far.\r\nWhen the purée is completely cold, adjust the sweetness to taste by adding more sugar if needed. Pour it into the bowl with the whipped cream and yoghurt and stir just once or twice until very lightly combined.\r\nSpoon the blackberry fool into individual wide, glass dishes – or one large, single bowl. It should look quite marbled, so don’t over-stir it. Scatter a few tiny mint leaves on top and decorate with the reserved blackberries. Sprinkle with a little sugar if you like and serve with the hazelnut biscuits.",
      strMealThumb:
        "https://www.themealdb.com/images/media/meals/rpvptu1511641092.jpg",
      strTags: "Desert,Summer,Fruity,Dairy",
      strYoutube: "https://www.youtube.com/watch?v=kniRGjDLFrQ",
      strIngredient1: "Hazlenuts",
      strIngredient2: "Butter",
      strIngredient3: "Caster Sugar",
      strIngredient4: "Lemon",
      strIngredient5: "Plain Flour",
      strIngredient6: "Baking Powder",
      strIngredient7: "Blackberrys",
      strIngredient8: "Sugar",
      strIngredient9: "Caster Sugar",
      strIngredient10: "Lemon Juice",
      strIngredient11: "Double Cream",
      strIngredient12: "Yogurt",
      strIngredient13: "Mint",
      strIngredient14: "",
      strIngredient15: "",
      strIngredient16: "",
      strIngredient17: "",
      strIngredient18: "",
      strIngredient19: "",
      strIngredient20: "",
      strMeasure1: "50g",
      strMeasure2: "125g",
      strMeasure3: "150g",
      strMeasure4: "Grated",
      strMeasure5: "150g",
      strMeasure6: "½ tsp",
      strMeasure7: "600g",
      strMeasure8: "75g",
      strMeasure9: "2 tbs",
      strMeasure10: "1 tbs",
      strMeasure11: "300ml ",
      strMeasure12: "100ml",
      strMeasure13: "Garnish with",
      strMeasure14: "",
      strMeasure15: "",
      strMeasure16: "",
      strMeasure17: "",
      strMeasure18: "",
      strMeasure19: "",
      strMeasure20: "",
      strSource:
        "https://www.bbc.co.uk/food/recipes/blackberry_fool_with_11859",
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: "53040",
      strMeal: "Spring onion and prawn empanadas",
      strDrinkAlternate: null,
      strCategory: "Seafood",
      strArea: "Portuguese",
      strInstructions:
        "STEP 1\r\n\r\nTo make the dough, rub the butter into the flour and then add the egg white and half the yolk (keep the rest), vinegar, a pinch of salt and enough cold water to make a soft dough. Knead on a floured surface until smooth and then wrap and rest for 30 minutes.\r\n\r\nSTEP 2\r\n\r\nHeat the oven to 180c/fan 160c/gas 4. Trim the green ends of the spring onions and then finely slice the rest. Heat a little oil in a pan and fry them gently until soft but not browned. Add the chilli and garlic, stir and then add the prawns and cook until they are opaque. Season well. Scoop out the prawns and bubble the juices until they thicken, then add back the prawns.\r\n\r\nSTEP 3\r\n\r\nDivide the empanada dough into eight balls and roll out to thin circles on a floured surface. Put some filling on one half of the dough, sprinkle the feta on top and fold the other half over. Trim the edge and then fold and crimp the dough together so the empanada is tightly sealed, put it on an oiled baking sheet either on its side or sitting on its un-crimped edge like a cornish pasty. Repeat with the remaining dough and mixture. Mix the leftover egg yolk with a splash of water and brush the top of the empanadas.\r\n\r\nSTEP 4\r\n\r\nBake for 30 minutes or until golden and slightly crisp around the edges.",
      strMealThumb:
        "https://www.themealdb.com/images/media/meals/1c5oso1614347493.jpg",
      strTags: null,
      strYoutube: "https://www.youtube.com/watch?v=Q24haJU-1dI",
      strIngredient1: "Spring Onions",
      strIngredient2: "Olive Oil",
      strIngredient3: "Red Chilli",
      strIngredient4: "Garlic",
      strIngredient5: "Prawns",
      strIngredient6: "Feta",
      strIngredient7: "Butter",
      strIngredient8: "Plain Flour",
      strIngredient9: "Egg",
      strIngredient10: "White Wine Vinegar",
      strIngredient11: "",
      strIngredient12: "",
      strIngredient13: "",
      strIngredient14: "",
      strIngredient15: "",
      strIngredient16: "",
      strIngredient17: "",
      strIngredient18: "",
      strIngredient19: "",
      strIngredient20: "",
      strMeasure1: "1  bunch",
      strMeasure2: "Dash",
      strMeasure3: "1 finely sliced",
      strMeasure4: "1 clove",
      strMeasure5: "350g",
      strMeasure6: "75g",
      strMeasure7: "15g",
      strMeasure8: "250g",
      strMeasure9: "1 Seperated",
      strMeasure10: "1/2 tsp",
      strMeasure11: " ",
      strMeasure12: " ",
      strMeasure13: " ",
      strMeasure14: " ",
      strMeasure15: " ",
      strMeasure16: " ",
      strMeasure17: " ",
      strMeasure18: " ",
      strMeasure19: " ",
      strMeasure20: " ",
      strSource:
        "https://www.olivemagazine.com/recipes/fish-and-seafood/spring-onion-and-prawn-empanadas/",
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: "53054",
      strMeal: "Seri muka kuih",
      strDrinkAlternate: null,
      strCategory: "Dessert",
      strArea: "Malaysian",
      strInstructions:
        "Soak glutinous rice with water for at least 1 ½ hours prior to using. Drain.\r\nPrepare a 9-inch round or square cake pan and spray with cooking spray or line with plastic wrap.\r\nMix coconut milk, water, salt and the rice. Pour it into cake pan, topped with the pandan knots.\r\nSteam for 30 minutes.\r\nAfter 30 minutes, fluff up the rice and remove pandan knots. Then, using a greased spatula, flatten the steamed rice. Make sure there are no holes/air bubbles and gaps in the rice, especially the sides.\r\nSteam for another 10 minutes.\r\n\r\nCombine pandan juice, coconut milk, all purpose flour, cornflour, and sugar. Mix well.\r\nAdd eggs and whisk well then strain into a medium sized metal bowl or pot.\r\nPlace pandan mixture over simmering water (double boiler or bain-marie)\r\nStir continuously and cook till custard starts to thicken. (15 minutes)\r\nPour pandan custard into glutinous rice layer, give it a little tap (for air bubbles) and continue to steam for 30 minutes.\r\nRemove kuih seri muka from the steamer and allow to cool completely before cutting into rectangles or diamond shapes.",
      strMealThumb:
        "https://www.themealdb.com/images/media/meals/6ut2og1619790195.jpg",
      strTags: null,
      strYoutube: "https://www.youtube.com/watch?v=_NJtCfqgaBo",
      strIngredient1: "Rice",
      strIngredient2: "Coconut Milk",
      strIngredient3: "Water",
      strIngredient4: "Salt",
      strIngredient5: "Corn Flour",
      strIngredient6: "Flour",
      strIngredient7: "Eggs",
      strIngredient8: "Coconut Cream",
      strIngredient9: "Sugar",
      strIngredient10: "",
      strIngredient11: "",
      strIngredient12: "",
      strIngredient13: "",
      strIngredient14: "",
      strIngredient15: "",
      strIngredient16: "",
      strIngredient17: "",
      strIngredient18: "",
      strIngredient19: "",
      strIngredient20: "",
      strMeasure1: "400g",
      strMeasure2: "150ml",
      strMeasure3: "100ml",
      strMeasure4: "1 tsp ",
      strMeasure5: "5 tbs",
      strMeasure6: "3 tbs",
      strMeasure7: "3",
      strMeasure8: "200ml",
      strMeasure9: "140g",
      strMeasure10: " ",
      strMeasure11: " ",
      strMeasure12: " ",
      strMeasure13: " ",
      strMeasure14: " ",
      strMeasure15: " ",
      strMeasure16: " ",
      strMeasure17: " ",
      strMeasure18: " ",
      strMeasure19: " ",
      strMeasure20: " ",
      strSource: "https://makan.ch/recipe/kuih-seri-muka/",
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: "52931",
      strMeal: "Sugar Pie",
      strDrinkAlternate: null,
      strCategory: "Dessert",
      strArea: "Canadian",
      strInstructions:
        "Preheat oven to 350 degrees F (175 degrees C). Grease a 9-inch pie dish.\r\nPlace the brown sugar and butter in a mixing bowl, and beat them together with an electric mixer until creamy and very well combined, without lumps. Beat in eggs, one at a time, incorporating the first egg before adding the next one. Add the vanilla extract and salt; beat the flour in, a little at a time, and then the milk, making a creamy batter. Pour the batter into the prepared pie dish.\r\nBake in the preheated oven for 35 minutes; remove pie, and cover the rim with aluminum foil to prevent burning. Return to oven, and bake until the middle sets and the top forms a crusty layer, about 15 more minutes. Let the pie cool to room temperature, then refrigerate for at least 1 hour before serving.",
      strMealThumb:
        "https://www.themealdb.com/images/media/meals/yrstur1511816601.jpg",
      strTags: "Pie,Desert",
      strYoutube: "https://www.youtube.com/watch?v=uVQ66jiL-Dc",
      strIngredient1: "Brown Sugar",
      strIngredient2: "Butter",
      strIngredient3: "Eggs",
      strIngredient4: "Vanilla Extract",
      strIngredient5: "Salt",
      strIngredient6: "Plain Flour",
      strIngredient7: "Milk",
      strIngredient8: "",
      strIngredient9: "",
      strIngredient10: "",
      strIngredient11: "",
      strIngredient12: "",
      strIngredient13: "",
      strIngredient14: "",
      strIngredient15: "",
      strIngredient16: "",
      strIngredient17: "",
      strIngredient18: "",
      strIngredient19: "",
      strIngredient20: "",
      strMeasure1: "2 cups ",
      strMeasure2: "¼ cup",
      strMeasure3: "2",
      strMeasure4: "1 tsp ",
      strMeasure5: "1 tsp ",
      strMeasure6: "½ cup ",
      strMeasure7: "1 1/2 cups ",
      strMeasure8: "",
      strMeasure9: "",
      strMeasure10: "",
      strMeasure11: "",
      strMeasure12: "",
      strMeasure13: "",
      strMeasure14: "",
      strMeasure15: "",
      strMeasure16: "",
      strMeasure17: "",
      strMeasure18: "",
      strMeasure19: "",
      strMeasure20: "",
      strSource:
        "http://allrecipes.com/recipe/213595/miraculous-canadian-sugar-pie/",
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
  ],
};
